### ISSUE TITLE
API

### ISSUE THREAD

**Issue by parisni** [CtrHellenicStudies/OpenVideoAnnotation#2]
Hi,

About the API, it there a way to get all the annotation within js ?

somethink like ova.getAnnotations();
and something like ova.restoreAnnotations(myAnnots);

 I have found them on annotatorjs (need to read the source ><) & annotoriousjs (api well described :) )

Thanks

**Comment by danielcebrian** [comment]
Hi, sorry for the delay, I did not see it until now.

You can get all the annotations in:
ova.annotator.plugins.Store.annotations

Best,
Daniel
