### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by garyfeng** [CtrHellenicStudies/OpenVideoAnnotation#3]
The following link/service in demo.html no longer works http://danielcebrian.com/annotations/api/search, nor does http://www.openvideoannotation.org/explore.php. Would you please update? Thanks!

**Comment by danielcebrian** [comment]
Now, it is working again. The icons are not working because of a cross-domain issue and I don't have access to the server. There is another example in https://gteavirtual.org/ova/index.php?r=site/page&view=explore with the icons
