### ISSUE TITLE
Licensing for Commercial use

### ISSUE THREAD

**Issue by 06samuen** [CtrHellenicStudies/OpenVideoAnnotation#5]
Hi 
Please could you let me know if this plugin can be used for commercial use. 
The only reason I ask is there are 2 different Licences from 2 different sites. 

One say yes the other say no?

Thanks 

Sam

**Comment by danielcebrian** [comment]
You can find the license for this js here: https://github.com/CtrHellenicStudies/OpenVideoAnnotation/blob/master/License.rst

There is just one for the js

**Comment by 06samuen** [comment]
Thanks, i will take a look, can you just confirm if we are able to use it with in our commercial product?

**Comment by danielcebrian** [comment]
Yes, your company can use GPL v2 code internally. The main restriction imposed by the GPL is that any source code derived from it or that uses it must also be released under the GPL, but if your company aren't modifying or distributing the original GPL code, then they can use the GPLed program.

**Comment by 06samuen** [comment]
So if we wanted to use the code as its for a SAAS software, is that possible? Sorry to be a pain :)

**Comment by danielcebrian** [comment]
yes, you can use it

**Comment by 06samuen** [comment]
Thanks for your help, real appreciated.

**Comment by danielcebrian** [comment]
No problem.

BTW, what does the software do? Do you have something online to see the results?
Best
